# Generated by Django 4.2.9 on 2025-06-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterKaryawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=256)),
                ('NIK', models.CharField(blank=True, max_length=256, null=True)),
                ('Alamat', models.CharField(blank=True, max_length=256, null=True)),
                ('Kontak', models.IntegerField(blank=True, null=True)),
                ('NPWP', models.CharField(blank=True, max_length=256, null=True)),
                ('NamaIbu', models.CharField(blank=True, max_length=256, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=256, null=True)),
                ('Status', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
