# Generated by Django 4.2.9 on 2026-04-05 14:56

import app.models
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeductionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='detailpayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BasicSalary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('AllowanceTotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('DeductionTotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('Tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('Status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid')], max_length=10)),
                ('Keterangan', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomorJO', models.CharField(max_length=256)),
                ('SalesOrder', models.CharField(max_length=256)),
                ('Client', models.CharField(blank=True, max_length=256, null=True)),
                ('Deskripsi', models.CharField(max_length=256)),
                ('Nilai', models.FloatField()),
                ('Invoice', models.FloatField()),
                ('Status', models.CharField(max_length=56)),
                ('Margin', models.FloatField()),
                ('Persen', models.FloatField()),
                ('StartWork', models.DateField()),
                ('EndWork', models.DateField()),
                ('TerminPembayaran', models.CharField(max_length=56)),
                ('FileKontrak', models.FileField(blank=True, null=True, upload_to='File/Project/JobOrder')),
            ],
        ),
        migrations.CreateModel(
            name='MasterJenisKaryawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JenisKaryawan', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='MasterMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KodeItem', models.CharField(max_length=50, unique=True)),
                ('NamaItem', models.CharField(max_length=128)),
                ('Satuan', models.CharField(blank=True, max_length=25, null=True)),
                ('SpesifikasiItem', models.CharField(max_length=256)),
                ('Stock', models.FloatField()),
                ('IsAset', models.BooleanField()),
                ('IsAktif', models.BooleanField()),
                ('Foto', models.ImageField(blank=True, null=True, upload_to=app.models.rename_fotomaterial)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialIssueSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tanggal', models.DateField()),
                ('NoMIS', models.CharField(max_length=72, unique=True)),
                ('FileMIS', models.FileField(blank=True, null=True, upload_to='File/Inventory/MIS')),
            ],
        ),
        migrations.CreateModel(
            name='Proyek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(blank=True, max_length=250, null=True)),
                ('Lokasi', models.CharField(blank=True, max_length=250, null=True)),
                ('Deskripsi', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NamaWarehouse', models.CharField(max_length=56)),
                ('Lokasi', models.CharField(max_length=56)),
                ('StatusPusat', models.BooleanField()),
                ('IsAktif', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorkCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomorWorkCompletion', models.CharField(max_length=256)),
                ('Tanggal', models.DateField()),
                ('Jenis', models.CharField(max_length=56)),
                ('Remarks', models.CharField(max_length=128)),
                ('Nilai', models.FloatField()),
                ('FileBA', models.FileField(blank=True, null=True, upload_to='File/Project/WorkCompletion')),
                ('NomorJO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.joborder')),
            ],
        ),
        migrations.CreateModel(
            name='WareHouseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('NomorTransfer', models.CharField(max_length=56, unique=True)),
                ('Status', models.CharField(max_length=56)),
                ('CreatedAt', models.DateTimeField(auto_now=True)),
                ('WarehouseAsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromwh', to='app.warehouse')),
                ('WarehouseTujuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towh', to='app.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='SuratJalan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tanggal', models.DateField()),
                ('NoSuratJalan', models.CharField(max_length=72, unique=True)),
                ('GoodReceiveNoted', models.FileField(blank=True, null=True, upload_to='File/Inventory/TransaksiMasuk')),
                ('JobOrder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.joborder')),
                ('WareHouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tanggal', models.DateField()),
                ('Keterangan', models.CharField(max_length=56)),
                ('Jumlah', models.FloatField()),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mastermaterial')),
                ('Warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodePayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KodePeriode', models.CharField(max_length=256)),
                ('TanggalAwal', models.DateField()),
                ('TanggalAkhir', models.DateField()),
                ('TanggalPembayaran', models.DateField(blank=True, null=True)),
                ('JenisPayroll', models.CharField(max_length=25)),
                ('Status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid')], max_length=10)),
                ('joborder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.joborder')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deduction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.deductiontype')),
                ('payroll_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='app.detailpayroll')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allowance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.allowancetype')),
                ('payroll_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='app.detailpayroll')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialMasuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jumlah', models.FloatField()),
                ('Remarks', models.CharField(blank=True, max_length=256, null=True)),
                ('NamaItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mastermaterial')),
                ('SuratJalan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.suratjalan')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialKeluar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jumlah', models.FloatField()),
                ('Remarks', models.CharField(max_length=50)),
                ('NamaItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mastermaterial')),
                ('NoMIS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.materialissueslip')),
            ],
        ),
        migrations.AddField(
            model_name='materialissueslip',
            name='WareHouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.warehouse'),
        ),
        migrations.CreateModel(
            name='MasterKaryawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=256)),
                ('NIK', models.CharField(blank=True, max_length=256, null=True)),
                ('Alamat', models.CharField(blank=True, max_length=256, null=True)),
                ('Kontak', models.IntegerField(blank=True, null=True)),
                ('NPWP', models.CharField(blank=True, max_length=256, null=True)),
                ('NOKK', models.CharField(blank=True, max_length=256, null=True)),
                ('Nama_Bank', models.CharField(blank=True, max_length=256, null=True)),
                ('NoRekening', models.CharField(blank=True, max_length=256, null=True)),
                ('NamaIbu', models.CharField(blank=True, max_length=256, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=256, null=True)),
                ('Status', models.CharField(blank=True, max_length=256, null=True)),
                ('FotoKTP', models.ImageField(blank=True, null=True, upload_to=app.models.rename_ktp)),
                ('FotoKK', models.ImageField(blank=True, null=True, upload_to=app.models.rename_kk)),
                ('FotoNPWP', models.ImageField(blank=True, null=True, upload_to=app.models.rename_npwp)),
                ('Gender', models.BooleanField(default=True)),
                ('PasFoto', models.ImageField(blank=True, null=True, upload_to=app.models.pasfoto)),
                ('JenisKaryawan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.masterjeniskaryawan')),
            ],
        ),
        migrations.CreateModel(
            name='Kontrak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomerKontrak', models.CharField(blank=True, max_length=256, null=True)),
                ('JenisKontrak', models.CharField(blank=True, max_length=250, null=True)),
                ('Durasi', models.IntegerField(default=0)),
                ('TanggalAwal', models.DateField()),
                ('TanggalAkhir', models.DateField()),
                ('Remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('StatusAktif', models.BooleanField(default=False)),
                ('File', models.FileField(blank=True, null=True, upload_to='File/HRIS/Kontrak')),
                ('Posisi', models.CharField(blank=True, max_length=250, null=True)),
                ('JobOrder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.joborder')),
                ('Nama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.masterkaryawan')),
                ('Proyek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.proyek')),
            ],
        ),
        migrations.CreateModel(
            name='DetailWareHouseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jumlah', models.FloatField()),
                ('NomorTransfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.warehousetransaction')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mastermaterial')),
            ],
        ),
        migrations.AddField(
            model_name='detailpayroll',
            name='Karyawan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.masterkaryawan'),
        ),
        migrations.AddField(
            model_name='detailpayroll',
            name='PeriodePayroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.periodepayroll'),
        ),
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tanggal', models.DateField()),
                ('StatusHadir', models.BooleanField()),
                ('Keterangan', models.CharField(blank=True, max_length=255, null=True)),
                ('Karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.masterkaryawan')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('Karyawan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.masterkaryawan')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
