# Generated by Django 6.0.3 on 2026-04-14 09:05

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CashExpenseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomorCashReport', models.CharField(max_length=256, unique=True)),
                ('Tanggal', models.DateField()),
                ('Remarks', models.CharField(max_length=128)),
                ('Nilai', models.FloatField()),
                ('FileCashReport', models.FileField(blank=True, null=True, upload_to='File/Project/CashReport')),
                ('Submittedby', models.CharField(blank=True, max_length=56, null=True)),
                ('Status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=10)),
                ('Approvedby', models.CharField(blank=True, max_length=56, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('approval_comments', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeductionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomorJO', models.CharField(max_length=256)),
                ('SalesOrder', models.CharField(max_length=256)),
                ('Client', models.CharField(blank=True, max_length=256, null=True)),
                ('Deskripsi', models.CharField(max_length=256)),
                ('Nilai', models.FloatField()),
                ('Invoice', models.FloatField()),
                ('Status', models.CharField(max_length=56)),
                ('Margin', models.FloatField()),
                ('Persen', models.FloatField()),
                ('StartWork', models.DateField()),
                ('EndWork', models.DateField()),
                ('TerminPembayaran', models.CharField(max_length=56)),
                ('FileKontrak', models.FileField(blank=True, null=True, upload_to='File/Project/JobOrder')),
            ],
        ),
        migrations.CreateModel(
            name='MasterJenisKaryawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JenisKaryawan', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='MasterMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KodeItem', models.CharField(max_length=50, unique=True)),
                ('NamaItem', models.CharField(max_length=128)),
                ('Satuan', models.CharField(blank=True, max_length=25, null=True)),
                ('SpesifikasiItem', models.CharField(max_length=256)),
                ('Stock', models.FloatField()),
                ('IsAset', models.BooleanField()),
                ('IsAktif', models.BooleanField()),
                ('Foto', models.ImageField(blank=True, null=True, upload_to=app.models.rename_fotomaterial)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialIssueSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tanggal', models.DateField()),
                ('NoMIS', models.CharField(max_length=72, unique=True)),
                ('FileMIS', models.FileField(blank=True, null=True, upload_to='File/Inventory/MIS')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kode', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Proyek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(blank=True, max_length=250, null=True)),
                ('Lokasi', models.CharField(blank=True, max_length=250, null=True)),
                ('Deskripsi', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NamaWarehouse', models.CharField(max_length=56)),
                ('Lokasi', models.CharField(max_length=56)),
                ('StatusPusat', models.BooleanField()),
                ('IsAktif', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aksi', models.CharField(max_length=255)),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCashExpenseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=256)),
                ('Jumlah', models.FloatField()),
                ('Harga', models.FloatField()),
                ('Satuan', models.CharField(blank=True, max_length=25, null=True)),
                ('TotalHarga', models.FloatField()),
                ('Remarks', models.CharField(blank=True, max_length=128, null=True)),
                ('NomorCashReport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.cashexpensereport')),
            ],
        ),
        migrations.CreateModel(
            name='MasterKaryawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=256)),
                ('NIK', models.CharField(blank=True, max_length=256, null=True)),
                ('Alamat', models.CharField(blank=True, max_length=256, null=True)),
                ('Kontak', models.IntegerField(blank=True, null=True)),
                ('NPWP', models.CharField(blank=True, max_length=256, null=True)),
                ('NOKK', models.CharField(blank=True, max_length=256, null=True)),
                ('Nama_Bank', models.CharField(blank=True, max_length=256, null=True)),
                ('NoRekening', models.CharField(blank=True, max_length=256, null=True)),
                ('NamaIbu', models.CharField(blank=True, max_length=256, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=256, null=True)),
                ('Status', models.CharField(blank=True, max_length=256, null=True)),
                ('FotoKTP', models.ImageField(blank=True, null=True, upload_to=app.models.rename_ktp)),
                ('FotoKK', models.ImageField(blank=True, null=True, upload_to=app.models.rename_kk)),
                ('FotoNPWP', models.ImageField(blank=True, null=True, upload_to=app.models.rename_npwp)),
                ('Gender', models.BooleanField(default=True)),
                ('PasFoto', models.ImageField(blank=True, null=True, upload_to=app.models.pasfoto)),
                ('JenisKaryawan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.masterjeniskaryawan')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='karyawan_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='detailpayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BasicSalary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('AllowanceTotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('DeductionTotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('Tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('Status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid')], max_length=10)),
                ('Keterangan', models.TextField(blank=True)),
                ('Karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.masterkaryawan')),
            ],
        ),
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tanggal', models.DateField()),
                ('StatusHadir', models.BooleanField()),
                ('Keterangan', models.CharField(blank=True, max_length=255, null=True)),
                ('Karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.masterkaryawan')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialKeluar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jumlah', models.FloatField()),
                ('Remarks', models.CharField(max_length=50)),
                ('NamaItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mastermaterial')),
                ('NoMIS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.materialissueslip')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allowance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.allowancetype')),
                ('payroll_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='app.detailpayroll')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deduction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.deductiontype')),
                ('payroll_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='app.detailpayroll')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodePayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KodePeriode', models.CharField(max_length=256)),
                ('TanggalAwal', models.DateField()),
                ('TanggalAkhir', models.DateField()),
                ('TanggalPembayaran', models.DateField(blank=True, null=True)),
                ('JenisPayroll', models.CharField(max_length=25)),
                ('Status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid')], max_length=10)),
                ('joborder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.joborder')),
            ],
        ),
        migrations.AddField(
            model_name='detailpayroll',
            name='PeriodePayroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.periodepayroll'),
        ),
        migrations.CreateModel(
            name='ProposedBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomorProposedBudget', models.CharField(max_length=256, unique=True)),
                ('Tanggal', models.DateField()),
                ('Remarks', models.CharField(max_length=128)),
                ('Nilai', models.FloatField()),
                ('FileProposedBudget', models.FileField(blank=True, null=True, upload_to='File/Project/ProposedBudget')),
                ('Submittedby', models.CharField(max_length=56)),
                ('Status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=10)),
                ('Approvedby', models.CharField(max_length=56)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('approval_comments', models.TextField(blank=True)),
                ('NomorJO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.joborder')),
            ],
        ),
        migrations.CreateModel(
            name='ItemProposedBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=256)),
                ('Jumlah', models.FloatField()),
                ('Satuan', models.CharField(blank=True, max_length=25, null=True)),
                ('Harga', models.FloatField()),
                ('TotalHarga', models.FloatField()),
                ('Remarks', models.CharField(blank=True, max_length=128, null=True)),
                ('NomorProposedBudget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.proposedbudget')),
            ],
        ),
        migrations.AddField(
            model_name='cashexpensereport',
            name='NomorProposedBudget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.proposedbudget'),
        ),
        migrations.CreateModel(
            name='Kontrak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomerKontrak', models.CharField(blank=True, max_length=256, null=True)),
                ('JenisKontrak', models.CharField(blank=True, max_length=250, null=True)),
                ('Durasi', models.IntegerField(default=0)),
                ('TanggalAwal', models.DateField()),
                ('TanggalAkhir', models.DateField()),
                ('Remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('StatusAktif', models.BooleanField(default=False)),
                ('File', models.FileField(blank=True, null=True, upload_to='File/HRIS/Kontrak')),
                ('Posisi', models.CharField(blank=True, max_length=250, null=True)),
                ('JobOrder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.joborder')),
                ('Nama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.masterkaryawan')),
                ('Proyek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.proyek')),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.role')),
            ],
        ),
        migrations.CreateModel(
            name='SuratJalan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tanggal', models.DateField()),
                ('NoSuratJalan', models.CharField(max_length=72, unique=True)),
                ('GoodReceiveNoted', models.FileField(blank=True, null=True, upload_to='File/Inventory/TransaksiMasuk')),
                ('JobOrder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.joborder')),
                ('WareHouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialMasuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jumlah', models.FloatField()),
                ('Remarks', models.CharField(blank=True, max_length=256, null=True)),
                ('NamaItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mastermaterial')),
                ('SuratJalan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.suratjalan')),
            ],
        ),
        migrations.CreateModel(
            name='UserProjectAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tanggal', models.DateField()),
                ('Keterangan', models.CharField(max_length=56)),
                ('Jumlah', models.FloatField()),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mastermaterial')),
                ('Warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='materialissueslip',
            name='WareHouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.warehouse'),
        ),
        migrations.CreateModel(
            name='WareHouseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('NomorTransfer', models.CharField(max_length=56, unique=True)),
                ('Status', models.CharField(max_length=56)),
                ('CreatedAt', models.DateTimeField(auto_now=True)),
                ('WarehouseAsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromwh', to='app.warehouse')),
                ('WarehouseTujuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towh', to='app.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='DetailWareHouseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jumlah', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mastermaterial')),
                ('NomorTransfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.warehousetransaction')),
            ],
        ),
        migrations.CreateModel(
            name='WorkCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomorWorkCompletion', models.CharField(max_length=256)),
                ('Tanggal', models.DateField()),
                ('Jenis', models.CharField(max_length=56)),
                ('Remarks', models.CharField(max_length=128)),
                ('Nilai', models.FloatField()),
                ('FileBA', models.FileField(blank=True, null=True, upload_to='File/Project/WorkCompletion')),
                ('NomorJO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.joborder')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tanggal', models.DateField()),
                ('NomorInvoice', models.CharField(max_length=256, unique=True)),
                ('Nilai', models.FloatField()),
                ('FileInvoice', models.FileField(blank=True, null=True, upload_to='File/Project/Invoice')),
                ('Status', models.CharField(max_length=56)),
                ('NomorWorkCompletion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.workcompletion')),
            ],
        ),
    ]
