# Generated by Django 6.0.3 on 2026-04-06 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashExpenseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomorCashReport', models.CharField(max_length=256)),
                ('Tanggal', models.DateField()),
                ('Jenis', models.CharField(max_length=56)),
                ('Remarks', models.CharField(max_length=128)),
                ('Nilai', models.FloatField()),
                ('FileCashReport', models.FileField(blank=True, null=True, upload_to='File/Project/CashReport')),
            ],
        ),
        migrations.CreateModel(
            name='itemCashExpenseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=256)),
                ('Jumlah', models.FloatField()),
                ('Harga', models.FloatField()),
                ('TotalHarga', models.FloatField()),
                ('Remarks', models.CharField(blank=True, max_length=128, null=True)),
                ('NomorCashReport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.cashexpensereport')),
            ],
        ),
        migrations.CreateModel(
            name='ProposedBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomorProposedBudget', models.CharField(max_length=256)),
                ('Tanggal', models.DateField()),
                ('Jenis', models.CharField(max_length=56)),
                ('Remarks', models.CharField(max_length=128)),
                ('Nilai', models.FloatField()),
                ('FileProposedBudget', models.FileField(blank=True, null=True, upload_to='File/Project/ProposedBudget')),
                ('Submittedby', models.CharField(max_length=56)),
                ('Status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=10)),
                ('Approvedby', models.CharField(max_length=56)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('approval_comments', models.TextField(blank=True)),
                ('NomorJO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.joborder')),
            ],
        ),
        migrations.CreateModel(
            name='ItemProposedBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=256)),
                ('Jumlah', models.FloatField()),
                ('Harga', models.FloatField()),
                ('TotalHarga', models.FloatField()),
                ('Remarks', models.CharField(blank=True, max_length=128, null=True)),
                ('NomorProposedBudget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.proposedbudget')),
            ],
        ),
        migrations.AddField(
            model_name='cashexpensereport',
            name='NomorProposedBudget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.proposedbudget'),
        ),
    ]
