# Generated by Django 4.2.9 on 2025-06-29 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='kontrak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomerKontrak', models.CharField(max_length=256)),
                ('TipeKontrak', models.CharField(choices=[('harian', 'Harian'), ('bulanan', 'Bulanan'), ('3_bulanan', '3 Bulanan'), ('6_bulanan', '6 Bulanan'), ('custom', 'Custom')], default='bulanan', max_length=30)),
                ('Durasi', models.IntegerField(default=1)),
                ('TanggalAwal', models.DateField()),
                ('TanggalAkhir', models.DateField()),
                ('Status', models.CharField(choices=[('aktif', 'Aktif'), ('berakhir', 'Berakhir'), ('diperpanjang', 'Diperpanjang')], default='aktif', max_length=30)),
                ('Remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('File', models.FileField(blank=True, null=True, upload_to='kontrak')),
                ('Nama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.masterkaryawan')),
            ],
        ),
    ]
