# Generated by Django 6.0.3 on 2026-04-22 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_budget_budgetitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetitem',
            name='budget',
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='app.joborder'),
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
