# Generated by Django 6.0.3 on 2026-04-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cashexpensereport_itemcashexpensereport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcashexpensereport',
            name='satuan',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='itemproposedbudget',
            name='Satuan',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
