# Generated by Django 4.2.9 on 2025-06-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_kontrak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontrak',
            name='File',
            field=models.FileField(blank=True, null=True, upload_to='File/HRIS/Kontrak'),
        ),
    ]
