# Generated by Django 4.2.9 on 2025-07-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_kontrak_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterkaryawan',
            name='FotoKTP',
            field=models.ImageField(blank=True, null=True, upload_to='ktp_images'),
        ),
        migrations.AddField(
            model_name='masterkaryawan',
            name='fotoKK',
            field=models.ImageField(blank=True, null=True, upload_to='kk_images'),
        ),
        migrations.AddField(
            model_name='masterkaryawan',
            name='fotoNPWP',
            field=models.ImageField(blank=True, null=True, upload_to='npwp_images'),
        ),
    ]
