# Generated by Django 6.0.3 on 2026-04-06 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_itemcashexpensereport_satuan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposedbudget',
            name='Jenis',
        ),
    ]
