# Generated by Django 6.0.3 on 2026-04-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_budgetitem_budget_budgetitem_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
