# Generated by Django 6.0.3 on 2026-04-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_budgetitem_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='budgetitem',
            name='level',
        ),
        migrations.RemoveField(
            model_name='budgetitem',
            name='parent',
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
