# Generated by Django 4.2.9 on 2025-07-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_masterkaryawan_fotoktp_masterkaryawan_fotokk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterkaryawan',
            name='NOKK',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
