# Generated by Django 6.0.3 on 2026-04-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_proposedbudget_jenis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposedbudget',
            name='NomorProposedBudget',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
