# Generated by Django 6.0.3 on 2026-04-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_budgetitem_created_at_remove_budgetitem_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='budgetitem',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='joborder',
            name='FileBudget',
            field=models.FileField(blank=True, null=True, upload_to='File/Project/Budget'),
        ),
    ]
