# Generated by Django 6.0.3 on 2026-04-07 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_proposedbudget_nomorproposedbudget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashexpensereport',
            name='Jenis',
        ),
    ]
