# Generated by Django 4.2.9 on 2025-07-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_proyek_remove_kontrak_durasi_remove_kontrak_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontrak',
            name='Posisi',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
