# Generated by Django 6.0.3 on 2026-04-22 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_budgetitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcashexpensereport',
            name='costcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.budgetitem'),
        ),
    ]
