# Generated by Django 6.0.3 on 2026-04-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_cashexpensereport_jenis'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashexpensereport',
            name='Approvedby',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='cashexpensereport',
            name='Status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='cashexpensereport',
            name='Submittedby',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='cashexpensereport',
            name='approval_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cashexpensereport',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
