# Generated by Django 4.2.9 on 2025-07-02 13:17

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_kontrak_posisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontrak',
            name='NomerKontrak',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='masterkaryawan',
            name='FotoKTP',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.rename_ktp),
        ),
        migrations.AlterField(
            model_name='masterkaryawan',
            name='fotoKK',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.rename_kk),
        ),
        migrations.AlterField(
            model_name='masterkaryawan',
            name='fotoNPWP',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.rename_npwp),
        ),
    ]
