# Generated by Django 6.0.3 on 2026-04-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_cashexpensereport_approvedby_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcashexpensereport',
            old_name='satuan',
            new_name='Satuan',
        ),
        migrations.AlterField(
            model_name='cashexpensereport',
            name='NomorCashReport',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
