# Generated by Django 6.0.3 on 2026-04-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_itemcashexpensereport_costcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterkaryawan',
            name='Role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
