# Generated by Django 6.0.3 on 2026-04-07 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_satuan_itemcashexpensereport_satuan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomorInvoice', models.CharField(max_length=256, unique=True)),
                ('Tanggal', models.DateField()),
                ('Nilai', models.FloatField()),
                ('FileInvoice', models.FileField(blank=True, null=True, upload_to='File/Project/Invoice')),
                ('Status', models.CharField(max_length=56)),
                ('NomorWorkCompletion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.workcompletion')),
            ],
        ),
    ]
