# Generated by Django 4.2.9 on 2025-07-02 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_kontrak_nomerkontrak_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterkaryawan',
            old_name='fotoKK',
            new_name='FotoKK',
        ),
        migrations.RenameField(
            model_name='masterkaryawan',
            old_name='fotoNPWP',
            new_name='FotoNPWP',
        ),
    ]
