# Generated by Django 4.2.9 on 2025-07-08 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_fotokk_masterkaryawan_fotokk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tanggal', models.DateField()),
                ('StatusHadir', models.BooleanField()),
                ('Keterangan', models.CharField(blank=True, max_length=255, null=True)),
                ('Karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.masterkaryawan')),
            ],
        ),
    ]
