# Generated by Django 6.0.3 on 2026-04-13 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Karyawan',
        ),
        migrations.AddField(
            model_name='masterkaryawan',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='karyawan_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
