# Generated by Django 4.2.9 on 2025-07-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_absensi'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterkaryawan',
            name='Nama_Bank',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='masterkaryawan',
            name='NoRekening',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
