# Generated by Django 6.0.3 on 2026-04-25 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_cashexpensereportapproval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashexpensereport',
            name='Approvedby',
        ),
        migrations.AlterField(
            model_name='cashexpensereport',
            name='Submittedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_cashreports', to=settings.AUTH_USER_MODEL),
        ),
    ]
