# Generated by Django 6.0.3 on 2026-04-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_cashexpensereport_approvedby_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashexpensereport',
            name='Submittedby',
        ),
        migrations.AddField(
            model_name='cashexpensereport',
            name='Approvedby',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
    ]
