# Generated by Django 4.2.9 on 2025-07-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_masterkaryawan_nama_bank_masterkaryawan_norekening'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterkaryawan',
            name='Gender',
            field=models.BooleanField(default=True),
        ),
    ]
