# Generated by Django 4.2.9 on 2025-07-11 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_masterkaryawan_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeductionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='detailpayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BasicSalary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('AllowanceTotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('DeductionTotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('Tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('Status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid')], max_length=10)),
                ('Keterangan', models.TextField(blank=True)),
                ('Karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.masterkaryawan')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodePayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KodePeriode', models.CharField(max_length=256)),
                ('TanggalAwal', models.DateField()),
                ('TanggalAkhir', models.DateField()),
                ('TanggalPembayaran', models.DateField()),
                ('JenisPayroll', models.CharField(max_length=25)),
                ('Status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deduction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.deductiontype')),
                ('payroll_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='app.detailpayroll')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allowance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.allowancetype')),
                ('payroll_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='app.detailpayroll')),
            ],
        ),
        migrations.AddField(
            model_name='detailpayroll',
            name='PeriodePayroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.periodepayroll'),
        ),
    ]
