# Generated by Django 4.2.9 on 2025-07-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_allowancetype_deductiontype_detailpayroll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodepayroll',
            name='TanggalPembayaran',
            field=models.DateField(blank=True, null=True),
        ),
    ]
