# Generated by Django 6.0.3 on 2026-04-25 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_cashexpensereport_submittedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposedbudget',
            name='Submittedby',
        ),
    ]
