# Generated by Django 4.2.9 on 2026-04-02 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_periodepayroll_tanggalpembayaran'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterJenisKaryawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JenisKaryawan', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='masterkaryawan',
            name='JenisKaryawan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.masterjeniskaryawan'),
        ),
    ]
