# Generated by Django 4.2.9 on 2026-04-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_masterjeniskaryawan_masterkaryawan_jeniskaryawan'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KodeItem', models.CharField(max_length=50, unique=True)),
                ('NamaItem', models.CharField(max_length=128)),
                ('SpesifikasiItem', models.CharField(max_length=256)),
                ('Stock', models.FloatField()),
                ('IsAset', models.BooleanField()),
                ('IsAktif', models.BooleanField()),
            ],
        ),
    ]
