# Generated by Django 6.0.3 on 2026-05-06 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_proposedbudget_submittedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashexpensereport',
            name='costcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.budgetitem'),
        ),
    ]
