# Generated by Django 4.2.9 on 2026-04-03 01:34

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_mastermaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastermaterial',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.rename_fotomaterial),
        ),
    ]
