# Generated by Django 6.0.3 on 2026-07-18 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_projectdocuments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdocuments',
            old_name='created_at',
            new_name='Created_at',
        ),
        migrations.RenameField(
            model_name='projectdocuments',
            old_name='created_by',
            new_name='Created_by',
        ),
        migrations.RenameField(
            model_name='projectdocuments',
            old_name='deskripsi',
            new_name='Deskripsi',
        ),
        migrations.RenameField(
            model_name='projectdocuments',
            old_name='file',
            new_name='File',
        ),
        migrations.RenameField(
            model_name='projectdocuments',
            old_name='last_modified_at',
            new_name='Last_modified_at',
        ),
        migrations.RenameField(
            model_name='projectdocuments',
            old_name='last_modified_by',
            new_name='Last_modified_by',
        ),
        migrations.RenameField(
            model_name='projectdocuments',
            old_name='nomor',
            new_name='Nomor',
        ),
        migrations.RenameField(
            model_name='projectdocuments',
            old_name='project',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='projectdocuments',
            old_name='tanggal',
            new_name='Tanggal',
        ),
        migrations.RenameField(
            model_name='projectdocuments',
            old_name='tipe',
            new_name='Tipe',
        ),
    ]
