# Generated by Django 4.2.9 on 2026-04-03 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_mastermaterial_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialMasuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tanggal', models.DateField()),
                ('Jumlah', models.FloatField()),
                ('NoSuratJalan', models.CharField(max_length=72)),
                ('GoodReceiveNoted', models.FileField(blank=True, null=True, upload_to='File/Inventory/TransaksiMasuk')),
                ('NamaItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mastermaterial')),
            ],
        ),
    ]
