# Generated by Django 4.2.9 on 2026-04-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_materialmasuk'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialmasuk',
            name='Remarks',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
