# Generated by Django 4.2.9 on 2026-04-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_materialmasuk_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastermaterial',
            name='Satuan',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
