# Generated by Django 4.2.9 on 2026-04-03 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_mastermaterial_satuan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuratJalan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tanggal', models.DateField()),
                ('NoSuratJalan', models.CharField(max_length=72, unique=True)),
                ('GoodReceiveNoted', models.FileField(blank=True, null=True, upload_to='File/Inventory/TransaksiMasuk')),
            ],
        ),
        migrations.RemoveField(
            model_name='materialmasuk',
            name='GoodReceiveNoted',
        ),
        migrations.RemoveField(
            model_name='materialmasuk',
            name='NoSuratJalan',
        ),
        migrations.RemoveField(
            model_name='materialmasuk',
            name='Tanggal',
        ),
        migrations.AddField(
            model_name='materialmasuk',
            name='SuratJalan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.suratjalan'),
        ),
    ]
