# Generated by Django 6.0.3 on 2026-07-18 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_userjoborder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjoborder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_job_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userjoborder',
            name='job_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='app.joborder'),
        ),
        migrations.AlterField(
            model_name='userjoborder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_order_access', to=settings.AUTH_USER_MODEL),
        ),
    ]
