# Generated by Django 6.0.3 on 2026-07-19 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_userjoborder_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=256)),
                ('Alamat', models.CharField(blank=True, max_length=256, null=True)),
                ('Kategori', models.CharField(blank=True, max_length=256, null=True)),
                ('PIC', models.CharField(blank=True, max_length=256, null=True)),
                ('Kontak', models.CharField(blank=True, max_length=256, null=True)),
                ('Email', models.EmailField(blank=True, max_length=256, null=True)),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomorPO', models.CharField(max_length=256, unique=True)),
                ('Tanggal', models.DateField()),
                ('Deskripsi', models.CharField(blank=True, max_length=256, null=True)),
                ('FilePO', models.FileField(blank=True, null=True, upload_to='File/Procurement/PO')),
                ('NomorJO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.joborder')),
                ('Vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vendormaster')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=256)),
                ('Jumlah', models.FloatField()),
                ('Satuan', models.CharField(blank=True, max_length=25, null=True)),
                ('Harga', models.FloatField()),
                ('TotalHarga', models.FloatField()),
                ('Remarks', models.CharField(blank=True, max_length=128, null=True)),
                ('NomorPO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='VendorQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomorQuotation', models.CharField(max_length=256, unique=True)),
                ('Tanggal', models.DateField()),
                ('Deskripsi', models.CharField(blank=True, max_length=256, null=True)),
                ('FileQuotation', models.FileField(blank=True, null=True, upload_to='File/Procurement/Quotation')),
                ('NomorJO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.joborder')),
                ('Vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vendormaster')),
            ],
        ),
        migrations.CreateModel(
            name='VendorQuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=256)),
                ('Jumlah', models.FloatField()),
                ('Satuan', models.CharField(blank=True, max_length=25, null=True)),
                ('Harga', models.FloatField()),
                ('TotalHarga', models.FloatField()),
                ('Remarks', models.CharField(blank=True, max_length=128, null=True)),
                ('NomorQuotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.vendorquotation')),
            ],
        ),
    ]
