# Generated by Django 4.2.9 on 2026-04-03 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_suratjalan_remove_materialmasuk_goodreceivenoted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialIssueSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tanggal', models.DateField()),
                ('NoMIS', models.CharField(max_length=72, unique=True)),
                ('FileMIS', models.FileField(blank=True, null=True, upload_to='File/Inventory/MIS')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialKeluar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jumlah', models.FloatField()),
                ('Remarks', models.CharField(max_length=50)),
                ('NamaItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mastermaterial')),
                ('NoMIS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.materialissueslip')),
            ],
        ),
    ]
