# Generated by Django 4.2.9 on 2026-04-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_materialissueslip_materialkeluar'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomorJO', models.CharField(max_length=256)),
                ('SalesOrder', models.CharField(max_length=256)),
                ('Deskripsi', models.CharField(max_length=256)),
                ('Nilai', models.FloatField()),
                ('Invoice', models.FloatField()),
                ('Status', models.CharField(max_length=56)),
                ('Margin', models.FloatField()),
                ('Persen', models.FloatField()),
                ('StartWork', models.DateField()),
                ('EndWork', models.DateField()),
                ('TerminPembayaran', models.CharField(max_length=56)),
                ('FileKontrak', models.FileField(blank=True, null=True, upload_to='File/Project/JobOrder')),
            ],
        ),
    ]
