# Generated by Django 6.0.3 on 2026-07-26 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_vendormaster_purchaseorder_purchaseorderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='ReferenceQuotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vendorquotation'),
        ),
    ]
