# Generated by Django 4.2.9 on 2026-04-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_joborder'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='Client',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
