# Generated by Django 6.0.3 on 2026-08-01 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_purchaseorder_referencequotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterkaryawan',
            name='TanggalLahir',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterkaryawan',
            name='JenisKaryawan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
