# Generated by Django 4.2.9 on 2026-04-04 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_joborder_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomorWorkCompletion', models.CharField(max_length=256)),
                ('Tanggal', models.DateField()),
                ('Jenis', models.CharField(max_length=56)),
                ('Remarks', models.CharField(max_length=128)),
                ('Nilai', models.FloatField()),
                ('FileKontrak', models.FileField(blank=True, null=True, upload_to='File/Project/WorkCompletion')),
                ('NomorJO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.joborder')),
            ],
        ),
    ]
