# Generated by Django 6.0.3 on 2026-08-01 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_masterkaryawan_tanggallahir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterkaryawan',
            name='JobOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='karyawan_joborder', to='app.joborder'),
        ),
    ]
