# Generated by Django 6.0.3 on 2026-08-02 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_masterkaryawan_joborder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodepayroll',
            old_name='joborder',
            new_name='NomorJO',
        ),
    ]
