# Generated by Django 4.2.9 on 2026-04-04 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_workcompletion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workcompletion',
            old_name='FileKontrak',
            new_name='FileBA',
        ),
    ]
