# Generated by Django 6.0.3 on 2026-08-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_rename_joborder_periodepayroll_nomorjo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailpayroll',
            name='NetSalary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
