# Generated by Django 4.2.9 on 2026-04-04 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_rename_filekontrak_workcompletion_fileba'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratjalan',
            name='JobOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.joborder'),
        ),
    ]
