# Generated by Django 4.2.9 on 2026-04-04 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_suratjalan_joborder'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontrak',
            name='Joborder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.joborder'),
        ),
    ]
