# Generated by Django 4.2.9 on 2026-04-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_kontrak_joborder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kontrak',
            old_name='Joborder',
            new_name='JobOrder',
        ),
    ]
