# Generated by Django 4.2.9 on 2026-04-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_rename_joborder_kontrak_joborder'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontrak',
            name='Durasi',
            field=models.IntegerField(default=0),
        ),
    ]
