# Generated by Django 4.2.9 on 2026-04-04 15:10

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_kontrak_durasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterkaryawan',
            name='PasFoto',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.pasfoto),
        ),
    ]
