# Generated by Django 4.2.9 on 2026-04-05 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_masterkaryawan_pasfoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodepayroll',
            name='joborder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.joborder'),
        ),
    ]
