# Generated by Django 4.2.9 on 2026-04-05 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_periodepayroll_joborder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NamaWarehouse', models.CharField(max_length=56)),
                ('Lokasi', models.CharField(max_length=56)),
                ('StatusPusat', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='WareHouseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('NomorTransfer', models.CharField(max_length=56, unique=True)),
                ('Status', models.CharField(max_length=56)),
                ('CreatedAt', models.DateTimeField(auto_now=True)),
                ('WarehouseAsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromwh', to='app.warehouse')),
                ('WarehouseTujuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towh', to='app.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tanggal', models.DateField()),
                ('Keterangan', models.CharField(max_length=56)),
                ('Jumlah', models.FloatField()),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mastermaterial')),
                ('Warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='DetailWareHouseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jumlah', models.FloatField()),
                ('NomorTransfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.warehousetransaction')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mastermaterial')),
            ],
        ),
    ]
