# Generated by Django 4.2.9 on 2026-04-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_warehouse_warehousetransaction_stockadjustment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='IsAktif',
            field=models.BooleanField(default=False),
        ),
    ]
