# Generated by Django 4.2.9 on 2026-04-05 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_warehouse_isaktif'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialissueslip',
            name='WareHouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.warehouse'),
        ),
        migrations.AddField(
            model_name='suratjalan',
            name='WareHouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.warehouse'),
        ),
    ]
